Traceback (most recent call last):
  File "/nix/store/qrkgxqbbr00qjik2rfqdw3z8a062s3ls-python3.8-jupyter-cache-0.4.2/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
icecream.plot(kind='bar', x='Flavor', y='Cones_Sold')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-10-ea93a57d5afd>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0micecream[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mkind[0m[0;34m=[0m[0;34m'bar'[0m[0;34m,[0m [0mx[0m[0;34m=[0m[0;34m'Flavor'[0m[0;34m,[0m [0my[0m[0;34m=[0m[0;34m'Cones_Sold'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/nix/store/mq2d2m2rf4m0hyrcj5qrh8yal4ff4zpc-python3-3.8.9-env/lib/python3.8/site-packages/babypandas/bpd.py[0m in [0;36mplot[0;34m(self, *args, **kwargs)[0m
[1;32m    755[0m         """
[1;32m    756[0m         [0mf[0m [0;34m=[0m [0m_lift_to_pd[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_pd[0m[0;34m.[0m[0mplot[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 757[0;31m         [0;32mreturn[0m [0mf[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    758[0m [0;34m[0m[0m
[1;32m    759[0m     [0;31m# IO[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/nix/store/mq2d2m2rf4m0hyrcj5qrh8yal4ff4zpc-python3-3.8.9-env/lib/python3.8/site-packages/babypandas/bpd.py[0m in [0;36mclosure[0;34m(*vargs, **kwargs)[0m
[1;32m   1531[0m                   for (k, x) in kwargs.items()}
[1;32m   1532[0m [0;34m[0m[0m
[0;32m-> 1533[0;31m         [0ma[0m [0;34m=[0m [0mfunc[0m[0;34m([0m[0;34m*[0m[0mvargs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1534[0m         [0;32mif[0m [0misinstance[0m[0;34m([0m[0ma[0m[0;34m,[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1535[0m             [0;32mreturn[0m [0mDataFrame[0m[0;34m([0m[0mdata[0m[0;34m=[0m[0ma[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/nix/store/mq2d2m2rf4m0hyrcj5qrh8yal4ff4zpc-python3-3.8.9-env/lib/python3.8/site-packages/pandas/plotting/_core.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
[1;32m    873[0m [0;34m[0m[0m
[1;32m    874[0m     [0;32mdef[0m [0m__call__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 875[0;31m         [0mplot_backend[0m [0;34m=[0m [0m_get_plot_backend[0m[0;34m([0m[0mkwargs[0m[0;34m.[0m[0mpop[0m[0;34m([0m[0;34m"backend"[0m[0;34m,[0m [0;32mNone[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    876[0m [0;34m[0m[0m
[1;32m    877[0m         x, y, kind, kwargs = self._get_call_args(

[0;32m/nix/store/mq2d2m2rf4m0hyrcj5qrh8yal4ff4zpc-python3-3.8.9-env/lib/python3.8/site-packages/pandas/plotting/_core.py[0m in [0;36m_get_plot_backend[0;34m(backend)[0m
[1;32m   1784[0m             [0;32mimport[0m [0mpandas[0m[0;34m.[0m[0mplotting[0m[0;34m.[0m[0m_matplotlib[0m [0;32mas[0m [0mmodule[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1785[0m         [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1786[0;31m             raise ImportError(
[0m[1;32m   1787[0m                 [0;34m"matplotlib is required for plotting when the "[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1788[0m                 [0;34m'default backend "matplotlib" is selected.'[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: matplotlib is required for plotting when the default backend "matplotlib" is selected.
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

